package com.lhx.jfinalone.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("login_log", "id", LoginLog.class);
		arp.addMapping("operate_log", "id", OperateLog.class);
		arp.addMapping("sys_group", "id", SysGroup.class);
		arp.addMapping("sys_user", "id", SysUser.class);
	}
}

