package com.lhx.jfinalone.entity;

import com.lhx.jfinalone.entity.base.BaseLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginLog extends BaseLoginLog<LoginLog> {
	public static final LoginLog dao = new LoginLog().dao();
}
