package com.lhx.jfinalone.entity;

import com.lhx.jfinalone.entity.base.BaseOperateLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperateLog extends BaseOperateLog<OperateLog> {
	public static final OperateLog dao = new OperateLog().dao();
}
