package com.lhx.jfinalone.entity;

import com.lhx.jfinalone.entity.base.BaseSysGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroup extends BaseSysGroup<SysGroup> {
	public static final SysGroup dao = new SysGroup().dao();
}
