package com.lhx.jfinalone.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGroupId(java.lang.Integer groupId) {
		set("groupId", groupId);
		return (M)this;
	}

	public java.lang.Integer getGroupId() {
		return getInt("groupId");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setUserAuth(java.lang.String userAuth) {
		set("userAuth", userAuth);
		return (M)this;
	}

	public java.lang.String getUserAuth() {
		return getStr("userAuth");
	}

	public M setCreater(java.lang.Integer creater) {
		set("creater", creater);
		return (M)this;
	}

	public java.lang.Integer getCreater() {
		return getInt("creater");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setLastLogin(java.util.Date lastLogin) {
		set("lastLogin", lastLogin);
		return (M)this;
	}

	public java.util.Date getLastLogin() {
		return get("lastLogin");
	}

}
