package com.lhx.jfinalone.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysGroup<M extends BaseSysGroup<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setGroupAuth(java.lang.String groupAuth) {
		set("groupAuth", groupAuth);
		return (M)this;
	}

	public java.lang.String getGroupAuth() {
		return getStr("groupAuth");
	}

	public M setCreater(java.lang.Integer creater) {
		set("creater", creater);
		return (M)this;
	}

	public java.lang.Integer getCreater() {
		return getInt("creater");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
