package com.lhx.jfinalone.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOperateLog<M extends BaseOperateLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setAccessName(java.lang.String accessName) {
		set("accessName", accessName);
		return (M)this;
	}

	public java.lang.String getAccessName() {
		return getStr("accessName");
	}

	public M setAccessPath(java.lang.String accessPath) {
		set("accessPath", accessPath);
		return (M)this;
	}

	public java.lang.String getAccessPath() {
		return getStr("accessPath");
	}

	public M setCreater(java.lang.Integer creater) {
		set("creater", creater);
		return (M)this;
	}

	public java.lang.Integer getCreater() {
		return getInt("creater");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public M setParams(java.lang.String params) {
		set("params", params);
		return (M)this;
	}

	public java.lang.String getParams() {
		return getStr("params");
	}

}
